/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, {useRef} from "react";
import {useGLTF} from "@react-three/drei";

export function Model(props) {
  const {nodes, materials} = useGLTF("/ivc.glb");
  return (
    <group {...props} dispose={null}>
      <group>
        <mesh castShadow receiveShadow geometry={nodes.A013.geometry} material={materials.aiStandardSurface1}>
          <group>
            <mesh castShadow receiveShadow geometry={nodes.A014_1.geometry} material={materials.aiStandardSurface2}>
              <mesh castShadow receiveShadow geometry={nodes.Cover.geometry} material={materials.aiStandardSurface2}>
                <mesh castShadow receiveShadow geometry={nodes.ventilation_R.geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes.ventilation_L.geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes.Paper.geometry} material={materials.C027_Main} />
                <mesh castShadow receiveShadow geometry={nodes.tray_H.geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes.tray_W.geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes.switch_L.geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes.polySurface14.geometry} material={materials.aiStandardSurface2} />
                </mesh>
                <mesh castShadow receiveShadow geometry={nodes.switch_R.geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes.polySurface20.geometry} material={materials.aiStandardSurface2} />
                </mesh>
              </mesh>
            </mesh>
            <mesh castShadow receiveShadow geometry={nodes.A014_2.geometry} material={materials.aiStandardSurface2} position={[0.247, 0, 0]}>
              <mesh castShadow receiveShadow geometry={nodes["Cover_(1)"].geometry} material={materials.aiStandardSurface2}>
                <mesh castShadow receiveShadow geometry={nodes["ventilation_R_(1)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["ventilation_L_(1)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["Paper_(1)"].geometry} material={materials.C027_Main} />
                <mesh castShadow receiveShadow geometry={nodes["tray_H_(1)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["tray_W_(1)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["switch_L_(1)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface14_(1)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
                <mesh castShadow receiveShadow geometry={nodes["switch_R_(1)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface20_(1)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
              </mesh>
            </mesh>
            <mesh castShadow receiveShadow geometry={nodes.A014_3.geometry} material={materials.aiStandardSurface2} position={[0.495, 0, 0]}>
              <mesh castShadow receiveShadow geometry={nodes["Cover_(2)"].geometry} material={materials.aiStandardSurface2}>
                <mesh castShadow receiveShadow geometry={nodes["ventilation_R_(2)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["ventilation_L_(2)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["Paper_(2)"].geometry} material={materials.C027_Main} />
                <mesh castShadow receiveShadow geometry={nodes["tray_H_(2)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["tray_W_(2)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["switch_L_(2)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface14_(2)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
                <mesh castShadow receiveShadow geometry={nodes["switch_R_(2)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface20_(2)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
              </mesh>
            </mesh>
            <mesh castShadow receiveShadow geometry={nodes.A014_4.geometry} material={materials.aiStandardSurface2} position={[0.742, 0, 0]}>
              <mesh castShadow receiveShadow geometry={nodes["Cover_(3)"].geometry} material={materials.aiStandardSurface2}>
                <mesh castShadow receiveShadow geometry={nodes["ventilation_R_(3)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["ventilation_L_(3)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["Paper_(3)"].geometry} material={materials.C027_Main} />
                <mesh castShadow receiveShadow geometry={nodes["tray_H_(3)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["tray_W_(3)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["switch_L_(3)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface14_(3)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
                <mesh castShadow receiveShadow geometry={nodes["switch_R_(3)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface20_(3)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
              </mesh>
            </mesh>
            <mesh castShadow receiveShadow geometry={nodes.A014_5.geometry} material={materials.aiStandardSurface2} position={[0.99, 0, 0]}>
              <mesh castShadow receiveShadow geometry={nodes["Cover_(4)"].geometry} material={materials.aiStandardSurface2}>
                <mesh castShadow receiveShadow geometry={nodes["ventilation_R_(4)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["ventilation_L_(4)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["Paper_(4)"].geometry} material={materials.C027_Main} />
                <mesh castShadow receiveShadow geometry={nodes["tray_H_(4)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["tray_W_(4)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["switch_L_(4)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface14_(4)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
                <mesh castShadow receiveShadow geometry={nodes["switch_R_(4)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface20_(4)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
              </mesh>
            </mesh>
            <mesh castShadow receiveShadow geometry={nodes.A014_6.geometry} material={materials.aiStandardSurface2} position={[1.237, 0, 0]}>
              <mesh castShadow receiveShadow geometry={nodes["Cover_(5)"].geometry} material={materials.aiStandardSurface2}>
                <mesh castShadow receiveShadow geometry={nodes["ventilation_R_(5)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["ventilation_L_(5)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["Paper_(5)"].geometry} material={materials.C027_Main} />
                <mesh castShadow receiveShadow geometry={nodes["tray_H_(5)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["tray_W_(5)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["switch_L_(5)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface14_(5)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
                <mesh castShadow receiveShadow geometry={nodes["switch_R_(5)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface20_(5)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
              </mesh>
            </mesh>
            <mesh castShadow receiveShadow geometry={nodes.A014_7.geometry} material={materials.aiStandardSurface2} position={[1.237, 0.279, 0]}>
              <mesh castShadow receiveShadow geometry={nodes["Cover_(6)"].geometry} material={materials.aiStandardSurface2}>
                <mesh castShadow receiveShadow geometry={nodes["ventilation_R_(6)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["ventilation_L_(6)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["Paper_(6)"].geometry} material={materials.C027_Main} />
                <mesh castShadow receiveShadow geometry={nodes["tray_H_(6)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["tray_W_(6)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["switch_L_(6)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface14_(6)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
                <mesh castShadow receiveShadow geometry={nodes["switch_R_(6)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface20_(6)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
              </mesh>
            </mesh>
            <mesh castShadow receiveShadow geometry={nodes.A014_8.geometry} material={materials.aiStandardSurface2} position={[0.99, 0.279, 0]}>
              <mesh castShadow receiveShadow geometry={nodes["Cover_(7)"].geometry} material={materials.aiStandardSurface2}>
                <mesh castShadow receiveShadow geometry={nodes["ventilation_R_(7)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["ventilation_L_(7)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["Paper_(7)"].geometry} material={materials.C027_Main} />
                <mesh castShadow receiveShadow geometry={nodes["tray_H_(7)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["tray_W_(7)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["switch_L_(7)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface14_(7)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
                <mesh castShadow receiveShadow geometry={nodes["switch_R_(7)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface20_(7)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
              </mesh>
            </mesh>
            <mesh castShadow receiveShadow geometry={nodes.A014_9.geometry} material={materials.aiStandardSurface2} position={[0.742, 0.279, 0]}>
              <mesh castShadow receiveShadow geometry={nodes["Cover_(8)"].geometry} material={materials.aiStandardSurface2}>
                <mesh castShadow receiveShadow geometry={nodes["ventilation_R_(8)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["ventilation_L_(8)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["Paper_(8)"].geometry} material={materials.C027_Main} />
                <mesh castShadow receiveShadow geometry={nodes["tray_H_(8)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["tray_W_(8)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["switch_L_(8)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface14_(8)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
                <mesh castShadow receiveShadow geometry={nodes["switch_R_(8)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface20_(8)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
              </mesh>
            </mesh>
            <mesh castShadow receiveShadow geometry={nodes.A014_10.geometry} material={materials.aiStandardSurface2} position={[0.495, 0.279, 0]}>
              <mesh castShadow receiveShadow geometry={nodes["Cover_(9)"].geometry} material={materials.aiStandardSurface2}>
                <mesh castShadow receiveShadow geometry={nodes["ventilation_R_(9)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["ventilation_L_(9)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["Paper_(9)"].geometry} material={materials.C027_Main} />
                <mesh castShadow receiveShadow geometry={nodes["tray_H_(9)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["tray_W_(9)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["switch_L_(9)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface14_(9)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
                <mesh castShadow receiveShadow geometry={nodes["switch_R_(9)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface20_(9)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
              </mesh>
            </mesh>
            <mesh castShadow receiveShadow geometry={nodes.A014_11.geometry} material={materials.aiStandardSurface2} position={[0.247, 0.279, 0]}>
              <mesh castShadow receiveShadow geometry={nodes["Cover_(10)"].geometry} material={materials.aiStandardSurface2}>
                <mesh castShadow receiveShadow geometry={nodes["ventilation_R_(10)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["ventilation_L_(10)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["Paper_(10)"].geometry} material={materials.C027_Main} />
                <mesh castShadow receiveShadow geometry={nodes["tray_H_(10)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["tray_W_(10)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["switch_L_(10)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface14_(10)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
                <mesh castShadow receiveShadow geometry={nodes["switch_R_(10)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface20_(10)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
              </mesh>
            </mesh>
            <mesh castShadow receiveShadow geometry={nodes.A014_12.geometry} material={materials.aiStandardSurface2} position={[0, 0.279, 0]}>
              <mesh castShadow receiveShadow geometry={nodes["Cover_(11)"].geometry} material={materials.aiStandardSurface2}>
                <mesh castShadow receiveShadow geometry={nodes["ventilation_R_(11)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["ventilation_L_(11)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["Paper_(11)"].geometry} material={materials.C027_Main} />
                <mesh castShadow receiveShadow geometry={nodes["tray_H_(11)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["tray_W_(11)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["switch_L_(11)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface14_(11)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
                <mesh castShadow receiveShadow geometry={nodes["switch_R_(11)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface20_(11)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
              </mesh>
            </mesh>
            <mesh castShadow receiveShadow geometry={nodes.A014_13.geometry} material={materials.aiStandardSurface2} position={[1.237, 0.559, 0]}>
              <mesh castShadow receiveShadow geometry={nodes["Cover_(12)"].geometry} material={materials.aiStandardSurface2}>
                <mesh castShadow receiveShadow geometry={nodes["ventilation_R_(12)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["ventilation_L_(12)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["Paper_(12)"].geometry} material={materials.C027_Main} />
                <mesh castShadow receiveShadow geometry={nodes["tray_H_(12)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["tray_W_(12)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["switch_L_(12)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface14_(12)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
                <mesh castShadow receiveShadow geometry={nodes["switch_R_(12)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface20_(12)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
              </mesh>
            </mesh>
            <mesh castShadow receiveShadow geometry={nodes.A014_14.geometry} material={materials.aiStandardSurface2} position={[0.99, 0.559, 0]}>
              <mesh castShadow receiveShadow geometry={nodes["Cover_(13)"].geometry} material={materials.aiStandardSurface2}>
                <mesh castShadow receiveShadow geometry={nodes["ventilation_R_(13)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["ventilation_L_(13)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["Paper_(13)"].geometry} material={materials.C027_Main} />
                <mesh castShadow receiveShadow geometry={nodes["tray_H_(13)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["tray_W_(13)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["switch_L_(13)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface14_(13)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
                <mesh castShadow receiveShadow geometry={nodes["switch_R_(13)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface20_(13)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
              </mesh>
            </mesh>
            <mesh castShadow receiveShadow geometry={nodes.A014_15.geometry} material={materials.aiStandardSurface2} position={[0.742, 0.559, 0]}>
              <mesh castShadow receiveShadow geometry={nodes["Cover_(14)"].geometry} material={materials.aiStandardSurface2}>
                <mesh castShadow receiveShadow geometry={nodes["ventilation_R_(14)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["ventilation_L_(14)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["Paper_(14)"].geometry} material={materials.C027_Main} />
                <mesh castShadow receiveShadow geometry={nodes["tray_H_(14)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["tray_W_(14)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["switch_L_(14)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface14_(14)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
                <mesh castShadow receiveShadow geometry={nodes["switch_R_(14)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface20_(14)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
              </mesh>
            </mesh>
            <mesh castShadow receiveShadow geometry={nodes.A014_16.geometry} material={materials.aiStandardSurface2} position={[0.495, 0.559, 0]}>
              <mesh castShadow receiveShadow geometry={nodes["Cover_(15)"].geometry} material={materials.aiStandardSurface2}>
                <mesh castShadow receiveShadow geometry={nodes["ventilation_R_(15)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["ventilation_L_(15)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["Paper_(15)"].geometry} material={materials.C027_Main} />
                <mesh castShadow receiveShadow geometry={nodes["tray_H_(15)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["tray_W_(15)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["switch_L_(15)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface14_(15)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
                <mesh castShadow receiveShadow geometry={nodes["switch_R_(15)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface20_(15)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
              </mesh>
            </mesh>
            <mesh castShadow receiveShadow geometry={nodes.A014_17.geometry} material={materials.aiStandardSurface2} position={[0.247, 0.559, 0]}>
              <mesh castShadow receiveShadow geometry={nodes["Cover_(16)"].geometry} material={materials.aiStandardSurface2}>
                <mesh castShadow receiveShadow geometry={nodes["ventilation_R_(16)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["ventilation_L_(16)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["Paper_(16)"].geometry} material={materials.C027_Main} />
                <mesh castShadow receiveShadow geometry={nodes["tray_H_(16)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["tray_W_(16)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["switch_L_(16)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface14_(16)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
                <mesh castShadow receiveShadow geometry={nodes["switch_R_(16)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface20_(16)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
              </mesh>
            </mesh>
            <mesh castShadow receiveShadow geometry={nodes.A014_18.geometry} material={materials.aiStandardSurface2} position={[0, 0.559, 0]}>
              <mesh castShadow receiveShadow geometry={nodes["Cover_(17)"].geometry} material={materials.aiStandardSurface2}>
                <mesh castShadow receiveShadow geometry={nodes["ventilation_R_(17)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["ventilation_L_(17)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["Paper_(17)"].geometry} material={materials.C027_Main} />
                <mesh castShadow receiveShadow geometry={nodes["tray_H_(17)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["tray_W_(17)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["switch_L_(17)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface14_(17)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
                <mesh castShadow receiveShadow geometry={nodes["switch_R_(17)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface20_(17)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
              </mesh>
            </mesh>
            <mesh castShadow receiveShadow geometry={nodes.A014_19.geometry} material={materials.aiStandardSurface2} position={[1.237, 0.839, 0]}>
              <mesh castShadow receiveShadow geometry={nodes["Cover_(18)"].geometry} material={materials.aiStandardSurface2}>
                <mesh castShadow receiveShadow geometry={nodes["ventilation_R_(18)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["ventilation_L_(18)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["Paper_(18)"].geometry} material={materials.C027_Main} />
                <mesh castShadow receiveShadow geometry={nodes["tray_H_(18)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["tray_W_(18)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["switch_L_(18)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface14_(18)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
                <mesh castShadow receiveShadow geometry={nodes["switch_R_(18)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface20_(18)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
              </mesh>
            </mesh>
            <mesh castShadow receiveShadow geometry={nodes.A014_20.geometry} material={materials.aiStandardSurface2} position={[0.99, 0.839, 0]}>
              <mesh castShadow receiveShadow geometry={nodes["Cover_(19)"].geometry} material={materials.aiStandardSurface2}>
                <mesh castShadow receiveShadow geometry={nodes["ventilation_R_(19)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["ventilation_L_(19)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["Paper_(19)"].geometry} material={materials.C027_Main} />
                <mesh castShadow receiveShadow geometry={nodes["tray_H_(19)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["tray_W_(19)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["switch_L_(19)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface14_(19)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
                <mesh castShadow receiveShadow geometry={nodes["switch_R_(19)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface20_(19)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
              </mesh>
            </mesh>
            <mesh castShadow receiveShadow geometry={nodes.A014_21.geometry} material={materials.aiStandardSurface2} position={[0.742, 0.839, 0]}>
              <mesh castShadow receiveShadow geometry={nodes["Cover_(20)"].geometry} material={materials.aiStandardSurface2}>
                <mesh castShadow receiveShadow geometry={nodes["ventilation_R_(20)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["ventilation_L_(20)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["Paper_(20)"].geometry} material={materials.C027_Main} />
                <mesh castShadow receiveShadow geometry={nodes["tray_H_(20)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["tray_W_(20)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["switch_L_(20)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface14_(20)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
                <mesh castShadow receiveShadow geometry={nodes["switch_R_(20)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface20_(20)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
              </mesh>
            </mesh>
            <mesh castShadow receiveShadow geometry={nodes.A014_22.geometry} material={materials.aiStandardSurface2} position={[0.495, 0.839, 0]}>
              <mesh castShadow receiveShadow geometry={nodes["Cover_(21)"].geometry} material={materials.aiStandardSurface2}>
                <mesh castShadow receiveShadow geometry={nodes["ventilation_R_(21)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["ventilation_L_(21)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["Paper_(21)"].geometry} material={materials.C027_Main} />
                <mesh castShadow receiveShadow geometry={nodes["tray_H_(21)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["tray_W_(21)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["switch_L_(21)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface14_(21)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
                <mesh castShadow receiveShadow geometry={nodes["switch_R_(21)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface20_(21)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
              </mesh>
            </mesh>
            <mesh castShadow receiveShadow geometry={nodes.A014_23.geometry} material={materials.aiStandardSurface2} position={[0.247, 0.839, 0]}>
              <mesh castShadow receiveShadow geometry={nodes["Cover_(22)"].geometry} material={materials.aiStandardSurface2}>
                <mesh castShadow receiveShadow geometry={nodes["ventilation_R_(22)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["ventilation_L_(22)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["Paper_(22)"].geometry} material={materials.C027_Main} />
                <mesh castShadow receiveShadow geometry={nodes["tray_H_(22)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["tray_W_(22)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["switch_L_(22)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface14_(22)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
                <mesh castShadow receiveShadow geometry={nodes["switch_R_(22)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface20_(22)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
              </mesh>
            </mesh>
            <mesh castShadow receiveShadow geometry={nodes.A014_24.geometry} material={materials.aiStandardSurface2} position={[0, 0.839, 0]}>
              <mesh castShadow receiveShadow geometry={nodes["Cover_(23)"].geometry} material={materials.aiStandardSurface2}>
                <mesh castShadow receiveShadow geometry={nodes["ventilation_R_(23)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["ventilation_L_(23)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["Paper_(23)"].geometry} material={materials.C027_Main} />
                <mesh castShadow receiveShadow geometry={nodes["tray_H_(23)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["tray_W_(23)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["switch_L_(23)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface14_(23)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
                <mesh castShadow receiveShadow geometry={nodes["switch_R_(23)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface20_(23)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
              </mesh>
            </mesh>
            <mesh castShadow receiveShadow geometry={nodes.A014_25.geometry} material={materials.aiStandardSurface2} position={[1.237, 1.119, 0]}>
              <mesh castShadow receiveShadow geometry={nodes["Cover_(24)"].geometry} material={materials.aiStandardSurface2}>
                <mesh castShadow receiveShadow geometry={nodes["ventilation_R_(24)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["ventilation_L_(24)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["Paper_(24)"].geometry} material={materials.C027_Main} />
                <mesh castShadow receiveShadow geometry={nodes["tray_H_(24)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["tray_W_(24)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["switch_L_(24)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface14_(24)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
                <mesh castShadow receiveShadow geometry={nodes["switch_R_(24)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface20_(24)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
              </mesh>
            </mesh>
            <mesh castShadow receiveShadow geometry={nodes.A014_26.geometry} material={materials.aiStandardSurface2} position={[0.99, 1.119, 0]}>
              <mesh castShadow receiveShadow geometry={nodes["Cover_(25)"].geometry} material={materials.aiStandardSurface2}>
                <mesh castShadow receiveShadow geometry={nodes["ventilation_R_(25)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["ventilation_L_(25)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["Paper_(25)"].geometry} material={materials.C027_Main} />
                <mesh castShadow receiveShadow geometry={nodes["tray_H_(25)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["tray_W_(25)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["switch_L_(25)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface14_(25)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
                <mesh castShadow receiveShadow geometry={nodes["switch_R_(25)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface20_(25)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
              </mesh>
            </mesh>
            <mesh castShadow receiveShadow geometry={nodes.A014_27.geometry} material={materials.aiStandardSurface2} position={[0.742, 1.119, 0]}>
              <mesh castShadow receiveShadow geometry={nodes["Cover_(26)"].geometry} material={materials.aiStandardSurface2}>
                <mesh castShadow receiveShadow geometry={nodes["ventilation_R_(26)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["ventilation_L_(26)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["Paper_(26)"].geometry} material={materials.C027_Main} />
                <mesh castShadow receiveShadow geometry={nodes["tray_H_(26)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["tray_W_(26)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["switch_L_(26)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface14_(26)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
                <mesh castShadow receiveShadow geometry={nodes["switch_R_(26)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface20_(26)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
              </mesh>
            </mesh>
            <mesh castShadow receiveShadow geometry={nodes.A014_28.geometry} material={materials.aiStandardSurface2} position={[0.495, 1.119, 0]}>
              <mesh castShadow receiveShadow geometry={nodes["Cover_(27)"].geometry} material={materials.aiStandardSurface2}>
                <mesh castShadow receiveShadow geometry={nodes["ventilation_R_(27)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["ventilation_L_(27)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["Paper_(27)"].geometry} material={materials.C027_Main} />
                <mesh castShadow receiveShadow geometry={nodes["tray_H_(27)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["tray_W_(27)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["switch_L_(27)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface14_(27)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
                <mesh castShadow receiveShadow geometry={nodes["switch_R_(27)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface20_(27)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
              </mesh>
            </mesh>
            <mesh castShadow receiveShadow geometry={nodes.A014_29.geometry} material={materials.aiStandardSurface2} position={[0.247, 1.119, 0]}>
              <mesh castShadow receiveShadow geometry={nodes["Cover_(28)"].geometry} material={materials.aiStandardSurface2}>
                <mesh castShadow receiveShadow geometry={nodes["ventilation_R_(28)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["ventilation_L_(28)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["Paper_(28)"].geometry} material={materials.C027_Main} />
                <mesh castShadow receiveShadow geometry={nodes["tray_H_(28)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["tray_W_(28)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["switch_L_(28)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface14_(28)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
                <mesh castShadow receiveShadow geometry={nodes["switch_R_(28)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface20_(28)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
              </mesh>
            </mesh>
            <mesh castShadow receiveShadow geometry={nodes.A014_30.geometry} material={materials.aiStandardSurface2} position={[0, 1.119, 0]}>
              <mesh castShadow receiveShadow geometry={nodes["Cover_(29)"].geometry} material={materials.aiStandardSurface2}>
                <mesh castShadow receiveShadow geometry={nodes["ventilation_R_(29)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["ventilation_L_(29)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["Paper_(29)"].geometry} material={materials.C027_Main} />
                <mesh castShadow receiveShadow geometry={nodes["tray_H_(29)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["tray_W_(29)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["switch_L_(29)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface14_(29)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
                <mesh castShadow receiveShadow geometry={nodes["switch_R_(29)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface20_(29)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
              </mesh>
            </mesh>
            <mesh castShadow receiveShadow geometry={nodes.A014_31.geometry} material={materials.aiStandardSurface2} position={[1.237, 1.401, 0]}>
              <mesh castShadow receiveShadow geometry={nodes["Cover_(30)"].geometry} material={materials.aiStandardSurface2}>
                <mesh castShadow receiveShadow geometry={nodes["ventilation_R_(30)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["ventilation_L_(30)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["Paper_(30)"].geometry} material={materials.C027_Main} />
                <mesh castShadow receiveShadow geometry={nodes["tray_H_(30)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["tray_W_(30)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["switch_L_(30)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface14_(30)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
                <mesh castShadow receiveShadow geometry={nodes["switch_R_(30)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface20_(30)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
              </mesh>
            </mesh>
            <mesh castShadow receiveShadow geometry={nodes.A014_32.geometry} material={materials.aiStandardSurface2} position={[0.99, 1.401, 0]}>
              <mesh castShadow receiveShadow geometry={nodes["Cover_(31)"].geometry} material={materials.aiStandardSurface2}>
                <mesh castShadow receiveShadow geometry={nodes["ventilation_R_(31)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["ventilation_L_(31)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["Paper_(31)"].geometry} material={materials.C027_Main} />
                <mesh castShadow receiveShadow geometry={nodes["tray_H_(31)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["tray_W_(31)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["switch_L_(31)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface14_(31)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
                <mesh castShadow receiveShadow geometry={nodes["switch_R_(31)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface20_(31)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
              </mesh>
            </mesh>
            <mesh castShadow receiveShadow geometry={nodes.A014_33.geometry} material={materials.aiStandardSurface2} position={[0.742, 1.401, 0]}>
              <mesh castShadow receiveShadow geometry={nodes["Cover_(32)"].geometry} material={materials.aiStandardSurface2}>
                <mesh castShadow receiveShadow geometry={nodes["ventilation_R_(32)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["ventilation_L_(32)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["Paper_(32)"].geometry} material={materials.C027_Main} />
                <mesh castShadow receiveShadow geometry={nodes["tray_H_(32)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["tray_W_(32)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["switch_L_(32)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface14_(32)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
                <mesh castShadow receiveShadow geometry={nodes["switch_R_(32)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface20_(32)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
              </mesh>
            </mesh>
            <mesh castShadow receiveShadow geometry={nodes.A014_34.geometry} material={materials.aiStandardSurface2} position={[0.495, 1.401, 0]}>
              <mesh castShadow receiveShadow geometry={nodes["Cover_(33)"].geometry} material={materials.aiStandardSurface2}>
                <mesh castShadow receiveShadow geometry={nodes["ventilation_R_(33)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["ventilation_L_(33)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["Paper_(33)"].geometry} material={materials.C027_Main} />
                <mesh castShadow receiveShadow geometry={nodes["tray_H_(33)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["tray_W_(33)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["switch_L_(33)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface14_(33)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
                <mesh castShadow receiveShadow geometry={nodes["switch_R_(33)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface20_(33)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
              </mesh>
            </mesh>
            <mesh castShadow receiveShadow geometry={nodes.A014_35.geometry} material={materials.aiStandardSurface2} position={[0.247, 1.401, 0]}>
              <mesh castShadow receiveShadow geometry={nodes["Cover_(34)"].geometry} material={materials.aiStandardSurface2}>
                <mesh castShadow receiveShadow geometry={nodes["ventilation_R_(34)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["ventilation_L_(34)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["Paper_(34)"].geometry} material={materials.C027_Main} />
                <mesh castShadow receiveShadow geometry={nodes["tray_H_(34)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["tray_W_(34)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["switch_L_(34)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface14_(34)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
                <mesh castShadow receiveShadow geometry={nodes["switch_R_(34)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface20_(34)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
              </mesh>
            </mesh>
            <mesh castShadow receiveShadow geometry={nodes.A014_36.geometry} material={materials.aiStandardSurface2} position={[0, 1.401, 0]}>
              <mesh castShadow receiveShadow geometry={nodes["Cover_(35)"].geometry} material={materials.aiStandardSurface2}>
                <mesh castShadow receiveShadow geometry={nodes["ventilation_R_(35)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["ventilation_L_(35)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["Paper_(35)"].geometry} material={materials.C027_Main} />
                <mesh castShadow receiveShadow geometry={nodes["tray_H_(35)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["tray_W_(35)"].geometry} material={materials.aiStandardSurface2} />
                <mesh castShadow receiveShadow geometry={nodes["switch_L_(35)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface14_(35)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
                <mesh castShadow receiveShadow geometry={nodes["switch_R_(35)"].geometry} material={materials.aiStandardSurface2}>
                  <mesh castShadow receiveShadow geometry={nodes["polySurface20_(35)"].geometry} material={materials.aiStandardSurface2} />
                </mesh>
              </mesh>
            </mesh>
          </group>
          <mesh castShadow receiveShadow geometry={nodes.wrapped_tube.geometry} material={materials.aiStandardSurface1} position={[0, -0.044, 0]} />
          <mesh castShadow receiveShadow geometry={nodes.Buckle4.geometry} material={materials.aiStandardSurface1} position={[0, -0.035, 0]} />
          <mesh castShadow receiveShadow geometry={nodes.Buckle3.geometry} material={materials.aiStandardSurface1} />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Buckle2.geometry}
            material={materials.aiStandardSurface1}
            position={[0.158, -0.309, 0.036]}
            scale={1.201}
          />
          <mesh castShadow receiveShadow geometry={nodes.Buckle1.geometry} material={materials.aiStandardSurface1} />
          <mesh castShadow receiveShadow geometry={nodes.Ventilation_line.geometry} material={materials.aiStandardSurface1} />
          <mesh castShadow receiveShadow geometry={nodes.Ventilation_line_switch.geometry} material={materials.aiStandardSurface1} />
          <mesh castShadow receiveShadow geometry={nodes.switches.geometry} material={materials.aiStandardSurface1} />
        </mesh>
        <group />
      </group>
    </group>
  );
}

useGLTF.preload("/ivc.glb");
